os: linux
dist: focal
group: edge
language: python
services:
  - docker
jobs:
  include:
    - script:
        - echo arthanaharidas
        - echo "${USER}"
        - docker login --username "arthanaharidas" --password "Udaya@123"
        - docker logout
        - python hello_world.py
